spring:
  rabbitmq:
    host: ${INFRA_RABBITMQ_HOST}
    port: ${INFRA_RABBITMQ_PORT}
    username: ${INFRA_RABBITMQ_USERNAME}
    password: ${INFRA_RABBITMQ_PASSWORD}
    virtual-host: ${INFRA_RABBITMQ_VHOST}
    ssl:
      enabled: true
    template:
      exchange: ${INFRA_RABBITMQ_EXCHANGE}
      routing-key: ${INFRA_RABBITMQ_ROUTING_KEY}
      default-receive-queue: ${INFRA_RABBITMQ_QUEUE}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
