server.port=${PORT:8080}

spring.jpa.open-in-view=false

b2.upload.part-size-mb=8
b2.upload.target-throughput-gbps=10.0

management.endpoints.web.exposure.include=health,info,loggers

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/doc
